feat(chatgpt): add theme
rose-pine/userstyles pull request #4
Opened 2023-10-24 06:12 UTC by adriankarlen

I couldn't highlight.js to work using imports so I ended up copying the hljs code to the css.

2023-11-12 20:45 UTC, mvllow requested changes
Sorry this took me a while to get to. Thank you for the new theme!

2023-11-12 20:45 UTC, mvllow commented on readme.md
> +-   [Proton](https://github.com/rose-pine/userstyles/tree/main/proton)
Please keep the same list formatting

2023-11-12 20:45 UTC, mvllow commented on readme.md
> +    - Then, click on the "Stylus Install" button or open `rose-pine.user.css` and click on "Raw."
Please keep the same list formatting

2023-11-12 20:45 UTC, mvllow commented on chatgpt/readme.md
> +![Rosé Pine Dawn](assets/dawn.webp)
Please use the GitHub CDN or another image host for these so they don't need to be part of the repo (:

2023-11-15 12:26 UTC, adriankarlen commented
Resolved the comments now.

2023-11-15 21:57 UTC, mvllow approved these changes

2023-11-16 07:56 UTC, merged